# Generated by Django 6.0.2 on 2026-02-26 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_users', models.PositiveIntegerField()),
                ('max_teams', models.PositiveIntegerField()),
                ('max_monthly_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('features', models.JSONField(blank=True, default=dict, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
            ],
            options={
                'db_table': 'subscription_plans',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionStatus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'subscription_status_lookup',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20, null=True)),
                ('next_recurring_date', models.DateField(blank=True, null=True)),
                ('forecast_for_next_month', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('allocated_to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='executive.team')),
                ('allocated_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='executive.organizationuser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executive.organization')),
            ],
            options={
                'db_table': 'budgets',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='executive.organization')),
                ('organization_user', models.ForeignKey(blank=True, db_column='organization_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='executive.organizationuser')),
                ('team', models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='executive.team')),
            ],
            options={
                'db_table': 'expense_logs',
                'abstract': False,
                'indexes': [models.Index(fields=['organization', 'created_at'], name='expense_log_organiz_bdbc66_idx'), models.Index(fields=['category'], name='expense_log_categor_4457ba_idx'), models.Index(fields=['organization', 'category'], name='expense_log_organiz_ab2c1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('from_entity_type', models.CharField(max_length=50)),
                ('from_entity_id', models.UUIDField()),
                ('to_entity_type', models.CharField(max_length=50)),
                ('to_entity_id', models.UUIDField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('is_caused_by_autopay', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='executive.organization')),
            ],
            options={
                'db_table': 'finance_audit_logs',
                'abstract': False,
                'indexes': [models.Index(fields=['organization', '-created_at'], name='finance_aud_organiz_3a8a54_idx')],
            },
        ),
    ]
