# Generated by Django 6.0.2 on 2026-02-27 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionstatus',
            options={'verbose_name': 'Subscription Status', 'verbose_name_plural': 'Subscription Status'},
        ),
    ]
