# Generated by Django 6.0.2 on 2026-03-03 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0004_alter_role_organization_alter_role_role_name'),
        ('finance', '0002_alter_subscriptionstatus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetApprovalStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Budget Approval Status',
                'verbose_name_plural': 'Budget Approval Status',
                'db_table': 'budget_approval_status_lookup',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField()),
                ('receipt_url', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by_user', to='executive.organizationuser')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='executive.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_by_user', to='executive.organizationuser')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_request_status', to='finance.budgetapprovalstatus')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='executive.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
