# Generated by Django 6.0.2 on 2026-02-26 09:29

import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userpasswordhistory_loginlog_mfadevice_and_more'),
        ('executive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='executive.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='id_token',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='refresh_token',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['user', 'provider'], name='social_acco_user_id_e2981d_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['organization', 'user'], name='user_profil_organiz_fbb669_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['email', 'login_attempt_time'], name='login_logs_email_7243c3_idx'),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mfadevice',
            unique_together={('user', 'device_name')},
        ),
    ]
