# Generated by Django 6.0.2 on 2026-02-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userprofile_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpasswordhistory',
            options={},
        ),
    ]
