# Generated by Django 6.0.2 on 2026-03-03 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userpasswordhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasswordhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
