# Generated by Django 6.0.2 on 2026-03-03 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userpasswordhistory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasswordhistory',
            name='user',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
