# Generated by Django 6.0.2 on 2026-02-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_userprofile_organization_and_more'),
        ('executive', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.ForeignKey(db_column='subscription_status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='finance.subscriptionstatus'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executive.organization'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='executive.organizationuser'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='executive.organization'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_user', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='executive.organizationuser'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='organization_user_status',
            field=models.ForeignKey(db_column='organization_user_status_id', on_delete=django.db.models.deletion.DO_NOTHING, to='executive.organizationuserstatus'),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executive.organization'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='executive.role'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='executive.role'),
        ),
        migrations.AddField(
            model_name='rolepermissionperorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executive.organization'),
        ),
        migrations.AddField(
            model_name='rolepermissionperorganization',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='executive.permission'),
        ),
        migrations.AddField(
            model_name='rolepermissionperorganization',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='executive.role'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(db_column='manager_teams', on_delete=django.db.models.deletion.PROTECT, to='executive.organizationuser'),
        ),
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='executive.organization'),
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='organization_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='executive.organizationuser'),
        ),
        migrations.AddField(
            model_name='teamassignment',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='executive.team'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('role_name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='organizationuser',
            index=models.Index(fields=['organization', 'role'], name='organizatio_organiz_49f94b_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['organization', 'email'], name='invitations_organiz_a9c159_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'organization')},
        ),
        migrations.AddIndex(
            model_name='rolepermissionperorganization',
            index=models.Index(fields=['organization', 'role'], name='role_permis_organiz_dabc53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermissionperorganization',
            unique_together={('role', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('organization', 'team_name')},
        ),
        migrations.AlterUniqueTogether(
            name='teamassignment',
            unique_together={('team', 'organization_user')},
        ),
    ]
