# Generated by Django 6.0.2 on 2026-02-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain_name',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
