# Generated by Django 6.0.2 on 2026-03-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0004_alter_role_organization_alter_role_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
