# Generated by Django 6.0.2 on 2026-03-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0005_role_role_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager_teams', null=True, on_delete=django.db.models.deletion.PROTECT, to='executive.organizationuser'),
        ),
    ]
